version: 2

references:

  container_config: &container_config
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          NS: registry.heroku.com
          HEROKU_APP: eil-kafka-topics-ui-stg

  install_heroku: &install_heroku
    run: |
      curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

jobs:

  build:
    <<: *container_config
    resource_class: large
    steps:
      - checkout
      - *install_heroku
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker Login
          command: docker login -username=$HEROKU_USERNAME --password=$HEROKU_API_KEY $NS
      - run:
          name: Docker Build
          command: |
            cd docker
            docker build -t $HEROKU_APP:$CIRCLE_SHA1 .
      - run:
          name: Docker Push
          command: |
            docker tag $HEROKU_APP:$CIRCLE_SHA1 $NS/$HEROKU_APP/web
            docker push $NS/$HEROKU_APP/web

  deploy_stg:
    <<: *container_config
    resource_class: small
    steps:
      - *install_heroku
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          heroku container:release web --app $HEROKU_APP

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build
      - deploy_stg:
          requires:
            - build
          filters:
            branches:
              only: infrastructure
