version: 2

references:

  container_config: &container_config
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          NS: registry.heroku.com
          HEROKU_APP: eil-kafka-topics-ui

  load_docker_cache: &load_docker_cache
    restore_cache:
      key: docker-cache-{{ .Branch }}-{{ .Revision }}

  install_heroku: &install_heroku
    run: |
      curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

jobs:

  build:
    <<: *container_config
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd docker
          heroku container:push web --app $HEROKU_APP

  deploy_stg:
    <<: *container_config
    resource_class: small
    steps:
      - *load_docker_cache
      - *install_heroku
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          heroku container:login
          heroku container:release web --app $HEROKU_APP

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build
      - deploy_stg:
          requires:
            - build
          filters:
            branches:
              only: infrastructure
