version: 2

references:

  container_config: &container_config
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          NS: registry.heroku.com
          HEROKU_APP: eil-kafka-topics-ui

  load_docker_cache: &load_docker_cache
    restore_cache:
      key: docker-cache-{{ .Branch }}-{{ .Revision }}

jobs:

  build:
    <<: *container_config
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd docker .
          docker build -t $HEROKU_APP:$CIRCLE_BRANCH-$CIRCLE_SHA1 .
      - run: |
          mkdir -p docker-cache
          docker save -o docker-cache/built-image.tar $HEROKU_APP:$CIRCLE_BRANCH-$CIRCLE_SHA1
      - save_cache:
          key: docker-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - docker/docker-cache

  deploy_stg:
    <<: *container_config
    resource_class: small
    steps:
      - *load_docker_cache
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          heroku container:login
          docker load < docker-cache/built-image.tar
          docker tag $HEROKU_APP:$CIRCLE_BRANCH-$CIRCLE_SHA1 $NS/$HEROKU_APP/web
          docker push $NS/$HEROKU_APP/web
          heroku container:release web --app $HEROKU_APP

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build
      - test_app:
          requires:
            - build
      - deploy_stg:
          requires:
            - test_app
          filters:
            branches:
              only: infrastructure
